#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, math
from pathlib import Path

MASK=0xffffffff
IV=[0x67452301,0xefcdab89,0x98badcfe,0x10325476,0xc3d2e1f0]
K=[0x5a827999,0x6ed9eba1,0x8f1bbcdc,0xca62c1d6]
CS=b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_"
def rol(x,n):return ((x<<n)&MASK)|(x>>(32-n))
def f(t,b,c,d):
    if t<20:return d^(b&(c^d))
    if t<40:return b^c^d
    if t<60:return (b&c)|(d&(b|c))
    return b^c^d
def compress(h,block):
    w=[int.from_bytes(block[i:i+4],'big') for i in range(0,64,4)]+[0]*64
    for t in range(16,80):w[t]=rol(w[t-3]^w[t-8]^w[t-14]^w[t-16],1)
    a,b,c,d,e=h
    for t in range(80):
        z=(rol(a,5)+f(t,b,c,d)+e+K[0 if t<20 else 1 if t<40 else 2 if t<60 else 3]+w[t])&MASK
        e,d,c,b,a=d,c,rol(b,30),a,z
    return [(h[0]+a)&MASK,(h[1]+b)&MASK,(h[2]+c)&MASK,(h[3]+d)&MASK,(h[4]+e)&MASK]
def git_object(payload):return b'commit '+str(len(payload)).encode()+b'\0'+payload
def sha1_pad(msg):
    x=bytearray(msg);n=len(x);x.append(0x80)
    while len(x)%64!=56:x.append(0)
    x+=(n*8).to_bytes(8,'big');return bytes(x)
def required_len(bits,alphabet,pfail):
    return math.ceil((bits+math.log2(-math.log(pfail)))/math.log2(alphabet))
def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('payload',type=Path)
    ap.add_argument('--nonce-len',type=int)
    ap.add_argument('--target-bits',type=int,default=32)
    ap.add_argument('--failure-prob',type=float,default=1e-6)
    ap.add_argument('--pad',type=int,default=7,help='fixed bytes between "Vanity: " and nonce for appended demo layout')
    ap.add_argument('--prefix',default='Vanity: ')
    ap.add_argument('--suffix',default='\n')
    ap.add_argument('--output-dir',type=Path,default=Path('job'))
    args=ap.parse_args()
    n=args.nonce_len or required_len(args.target_bits,64,args.failure_prob)
    src=args.payload.read_bytes(); src0=src if (not src or src.endswith(b'\n')) else src+b'\n'
    placeholder=b'N'*n
    add=args.prefix.encode()+b'P'*args.pad+placeholder+args.suffix.encode()
    payload=src0+add
    nonce_payload_off=len(src0)+len(args.prefix.encode())+args.pad
    obj=git_object(payload); nonce_abs=len(b'commit '+str(len(payload)).encode()+b'\0')+nonce_payload_off
    if nonce_abs//64 != (nonce_abs+n-1)//64: raise SystemExit('nonce crosses SHA-1 block; choose another layout')
    mod=len(obj)%64
    if mod>55: raise SystemExit(f'not tail1: unpadded object mod64={mod} requires a second padding block')
    block_index=nonce_abs//64
    if block_index != len(obj)//64: raise SystemExit('nonce is not in final data block')
    padded=sha1_pad(obj); final=bytearray(padded[block_index*64:(block_index+1)*64])
    noff=nonce_abs&63
    for i in range(n): final[noff+i]=0
    h=IV[:]
    for i in range(block_index): h=compress(h,padded[i*64:(i+1)*64])
    base16=[int.from_bytes(final[i:i+4],'big') for i in range(0,64,4)]
    out=args.output_dir;out.mkdir(parents=True,exist_ok=True)
    header=out/'job_constants.cuh'
    header.write_text('// generated by prepare_git_job.py\n#pragma once\n#include <stdint.h>\n'+
      'static constexpr uint32_t JOB_BASE16[16]={'+','.join(f'0x{x:08x}u' for x in base16)+'};\n'+
      'static constexpr uint32_t JOB_HIN[5]={'+','.join(f'0x{x:08x}u' for x in h)+'};\n')
    flags=f'-DNONCE_OFF={noff} -DNONCE_LEN={n} -DDATA_LEN={mod} -DPREFIX_BLOCKS={block_index} -DJOB_CONSTANTS_HEADER=\\\"job_constants.cuh\\\"'
    (out/'nvcc_flags.txt').write_text(flags+'\n')
    manifest={
      'payload_bytes':len(payload),'git_object_unpadded_bytes':len(obj),'git_header_bytes':len(obj)-len(payload),
      'nonce_payload_offset':nonce_payload_off,'nonce_absolute_offset':nonce_abs,'nonce_final_block_offset':noff,
      'nonce_len':n,'first_mutable_block':block_index,'first_mutable_word':noff//4,'data_len_in_final_block':mod,
      'tail1':True,'prefix_blocks':block_index,'base16':[f'{x:08x}' for x in base16],'hin':[f'{x:08x}' for x in h],
      'placeholder_object_sha1':hashlib.sha1(obj).hexdigest(),'nvcc_flags':flags,
    }
    (out/'payload_template.bin').write_bytes(payload)
    (out/'job.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(json.dumps(manifest,indent=2))
if __name__=='__main__':main()
